# .github/workflows/test-build.yml
name: Test build

on:
  push:
    branches: [feature/add-ci]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check that repo is accessible
        run: ls -la